### ISSUE TITLE
Resolution of reconstruction results on EPFL dataset

### ISSUE THREAD

**Issue by hmzawz2** [cbmi-group/IsoVEM#2]
Hello, recently I have been reproducing your work based on the EPFL dataset. For calculating the resolution of reconstruction results, I used the code from [repository](https://github.com/HaoChengGao/FSC_SMLM) to calculate (parameters are sz=512, psz=5nm zm=1). Under this set of parameters, the calculated resolution of IsoVEM is 27.9nm. Could you please share your calculating code of FSC and parameters were used to calculate the FSC resolution in the IsoVEM paper? Thank you in advance!
![image](https://github.com/cbmi-group/IsoVEM/assets/27480770/5d1bf785-e12f-47ce-a30a-1a20273c1593)

**Comment by yanzhang81** [comment]
Hi Hmzawz2，we used the program EMAN2 to calculate the FSC，the specific command we used is: e2proc3d.py model1  --calcfsc=model2 fsc.txt. You can replace the model1 and model2 with your file, and all cross-correlation values are contained in the fsc.txt. Don't hesitate to contact us if you have further problems.

**Comment by hmzawz2** [comment]
Thanks, I will do more test.
